[book]
authors = ["James 555, Teddy 5461"]
language = "zh"
multilingual = false
src = "src"
title = "Programming for FRC"

[preprocessor.theme]
pagetoc = true
sidebar-width = "250px"

[output.html]
default-theme = "ayu"
git-repository-url = ""
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = true

[output.html.print]
enable = false

[output.theme-ace]
theme-white = "xcode"
theme-dark = "monokai"
